Repository legm0310/SafeTransactionPlatform, pull requests merged in 2023-06, with the labels that each got.

#87 Refactor: Header.js 수정
  client/package-lock.json
  client/package.json
  client/src/components/Home/Home.module.css
  client/src/components/Layout/Header.js
  client/src/components/Layout/Header.module.css
  client/src/components/Product/Product.js
  client/src/components/Product/Product.module.css
Labels: 🌈 Frontend, 🔨 Refactor

#88 Fix: multer사용 메소드 변경
  server/middlewares/uploader.js
  server/package-lock.json
  server/package.json
  server/routes/product.js
Labels: 📬 API, 🐞 Fix, ⚙ Chore

#89 Feat: 유효성 검증
  server/config/validSchema.js
  server/middlewares/validation.js
Labels: 📬 API, ✨ Feat

#90 Fix: signup 유효성 검증 id 제거 및 예외처리 수정
  server/config/validSchema.js
  server/controllers/productController.js
  server/loaders/express.js
  server/middlewares/error.js
  server/middlewares/uploader.js
  server/middlewares/validation.js
  server/models/product.js
  server/routes/product.js
  server/services/product.js
Labels: 📬 API, 🐞 Fix

#91 Fix: formData에 json데이터 추가
  client/src/components/AddProduct/AddProduct.js
Labels: 🌈 Frontend, 🐞 Fix, ✨ Feat

#92 Refactor: axios요청 모듈화
  client/src/_actions/productAction.js
  client/src/_actions/userAction.js
  client/src/_reducers/userReducer.js
  client/src/api/common.js
  client/src/api/productApi.js
  client/src/components/Auth/Login.module.css
  client/src/components/Home/Home.module.css
  client/src/components/Layout/Header.js
  client/src/components/Layout/Header.module.css
  client/src/index.css
  client/src/utils/index.js
  client/src/utils/storage.js
Labels: 🌈 Frontend, 🎨 Design, 🔨 Refactor

#93 Fix: db 관계 설정 오류 수정
  server/models/product.js
  server/models/user.js
Labels: 📬 API, 🐞 Fix

#94 Feat: getProduct 구현
  server/controllers/productController.js
  server/models/chatLog.js
  server/models/index.js
  server/models/product.js
  server/models/productImage.js
  server/routes/product.js
  server/services/product.js
Labels: 📬 API, 🐞 Fix, ✨ Feat

#95 Rename: 파일 구조화, Refactor: 파일 구조화로 인한 import 경로 변경
  client/src/App.js
  client/src/components/Layout/DropdownMenu.js
  client/src/components/Layout/Header.js
  client/src/components/Layout/UserAuth.js
  client/src/components/Sale/Sale.js
  client/src/components/Sale/Sale.module.css
  client/src/pages/AddProduct/AddProduct.js
  client/src/pages/Auth/Login.js
  client/src/pages/Auth/Register.js
  client/src/pages/Home/Home.js
  client/src/pages/Home/HomeSlide.js
  client/src/pages/Product/Detail.js
  client/src/pages/Product/DetailSlide.js
  client/src/pages/Product/Product.js
  client/src/pages/Product/ProductCard.js
  client/src/styles/AddProduct.module.css
  client/src/styles/Detail.module.css
  client/src/styles/DetailSlide.module.css
  client/src/styles/DropdownMenu.module.css
  client/src/styles/Header.module.css
  client/src/styles/Home.module.css
  client/src/styles/HomeSlide.module.css
  client/src/styles/Login.module.css
  client/src/styles/Product.module.css
  client/src/styles/ProductCard.module.css
  client/src/styles/Register.module.css
  client/src/styles/UserAuth.module.css
  package-lock.json
Labels: 🌈 Frontend, 🔨 Refactor

#96 Refactor: 헤더 컴포넌트로 분할
  client/src/components/Layout/DesktopNavMenu.js
  client/src/components/Layout/Header.js
  client/src/components/Layout/Logo.js
  client/src/components/Layout/MobileNavMenu.js
  client/src/components/Layout/UserAuth.js
  client/src/styles/UserAuth.module.css
Labels: 🌈 Frontend, 🔨 Refactor, ✨ Feat

#97 Feat: getProducts구현, data parse 분리
  server/controllers/productController.js
  server/loaders/sequelize.js
  server/middlewares/error.js
  server/models/product.js
  server/package-lock.json
  server/package.json
  server/routes/product.js
  server/seeders/20230604184326-product.js
  server/services/product.js
  server/utils/index.js
  server/utils/parse.js
Labels: 📬 API, 🐞 Fix, ✨ Feat, ⚙ Chore, ✅ Test

#98 Merge: client -> dev
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/_actions/productAction.js
  client/src/_actions/type.js
  client/src/_actions/userAction.js
  client/src/_reducers/index.js
  client/src/_reducers/productReducer.js
  client/src/_reducers/userReducer.js
  client/src/api/common.js
  client/src/api/productApi.js
  client/src/assets/test.jpg
  client/src/assets/testImg.png
  client/src/components/Layout/DesktopNavMenu.js
  client/src/components/Layout/DropdownMenu.js
  client/src/components/Layout/Header.js
  client/src/components/Layout/Logo.js
  client/src/components/Layout/MobileNavMenu.js
  client/src/components/Layout/UserAuth.js
  client/src/components/Purchase/Detail.js
  client/src/components/Purchase/Detail.module.css
  client/src/components/Purchase/Purchase.js
  client/src/components/Sale/Sale.js
  client/src/components/Sale/Sale.module.css
  client/src/hoc/auth.js
  client/src/index.css
  client/src/index.js
  client/src/pages/AddProduct/AddProduct.js
  client/src/pages/Auth/Login.js
  client/src/pages/Auth/Register.js
  client/src/pages/Home/Home.js
  client/src/pages/Home/HomeSlide.js
  client/src/pages/Product/Detail.js
  client/src/pages/Product/DetailSlide.js
  client/src/pages/Product/Product.js
  client/src/pages/Product/ProductCard.js
  client/src/styles/AddProduct.module.css
  client/src/styles/Detail.module.css
  client/src/styles/DetailSlide.module.css
  client/src/styles/DropdownMenu.module.css
  client/src/styles/Header.module.css
  client/src/styles/Home.module.css
  client/src/styles/HomeSlide.module.css
  client/src/styles/Login.module.css
  client/src/styles/Product.module.css
  client/src/styles/ProductCard.module.css
  client/src/styles/Register.module.css
  client/src/styles/UserAuth.module.css
  client/src/utils/index.js
  client/src/utils/storage.js
  package-lock.json
Labels: 🌈 Frontend, 🔀 Merge

#99 Merge: server -> dev
  server/config/index.js
  server/config/passport.js
  server/config/validSchema.js
  server/controllers/authController.js
  server/controllers/productController.js
  server/loaders/express.js
  server/loaders/sequelize.js
  server/middlewares/error.js
  server/middlewares/index.js
  server/middlewares/isAuth.js
  server/middlewares/uploader.js
  server/middlewares/validation.js
  server/models/chatLog.js
  server/models/index.js
  server/models/product.js
  server/models/productImage.js
  server/models/user.js
  server/package-lock.json
  server/package.json
  server/routes/auth.js
  server/routes/index.js
  server/routes/product.js
  server/seeders/20230604184326-product.js
  server/services/auth.js
  server/services/product.js
  server/services/token.js
  server/utils/generalError.js
  server/utils/index.js
  server/utils/parse.js
  server/utils/s3Upload.js
Labels: 📬 API, 🔀 Merge

#101 Refactor: dependencyInjector 수정
  server/config/index.js
  server/loaders/containerObject.js
  server/loaders/dependencyConvert.js
  server/loaders/dependencyInjector.js
  server/loaders/index.js
  server/middlewares/validation.js
  server/models/index.js
Labels: 📬 API, 🐞 Fix, 🔨 Refactor

#103 Merge: dev -> main
  client/src/_actions/productAction.js
  package-lock.json
Labels: 🌈 Frontend, 🐞 Fix, 🔀 Merge

#104 Feat: getProducts 쿼리 생성코드 분리
  server/controllers/productController.js
  server/loaders/sequelize.js
  server/models/product.js
  server/seeders/20230604184326-product.js
  server/services/product.js
  server/test/MOCK_DATA.json
  server/utils/ApiError.js
  server/utils/dataParsers.js
  server/utils/generalError.js
  server/utils/index.js
  server/utils/parse.js
Labels: 📬 API, 🐞 Fix, 🔨 Refactor, ✨ Feat, ✅ Test

#109 Merge: client -> dev
  client/src/_actions/productAction.js
  client/src/_actions/type.js
  client/src/_reducers/productReducer.js
  client/src/assets/platformImage.png
  client/src/assets/platformImage1.png
  client/src/assets/platformImage2.png
  client/src/assets/platformImage3.png
  client/src/assets/platformImage4.png
  client/src/components/Layout/DesktopNavMenu.js
  client/src/components/Layout/Logo.js
  client/src/components/Layout/MobileNavMenu.js
  client/src/components/Layout/MyWallet.js
  client/src/components/Layout/UserAuth.js
  client/src/components/Layout/UserSection.js
  client/src/components/RecentProductsList.js
  client/src/pages/Home/Home.js
  client/src/styles/Home.module.css
  client/src/styles/RecentProductsList.module.css
  client/src/styles/UserAuth.module.css
Labels: 🌈 Frontend, 🔀 Merge

#110 Merge: dev -> main
  client/src/_actions/productAction.js
  client/src/_actions/type.js
  client/src/_reducers/productReducer.js
  client/src/assets/platformImage.png
  client/src/assets/platformImage1.png
  client/src/assets/platformImage2.png
  client/src/assets/platformImage3.png
  client/src/assets/platformImage4.png
  client/src/components/Layout/DesktopNavMenu.js
  client/src/components/Layout/Logo.js
  client/src/components/Layout/MobileNavMenu.js
  client/src/components/Layout/MyWallet.js
  client/src/components/Layout/UserAuth.js
  client/src/components/Layout/UserSection.js
  client/src/components/RecentProductsList.js
  client/src/pages/Home/Home.js
  client/src/styles/Home.module.css
  client/src/styles/RecentProductsList.module.css
  client/src/styles/UserAuth.module.css
Labels: 🌈 Frontend, 🔀 Merge

#111 Feat: UserAuth.js Fragment추가
  client/src/components/Layout/MobileNavMenu.js
  client/src/components/Layout/UserAuth.js
  client/src/components/Layout/UserSection.js
  client/src/styles/UserAuth.module.css
Labels: 🌈 Frontend, 🎨 Design, ✨ Feat, 📃 Docs

#112 Feat: 리렌더링시 로그인여부확인, 재사용 버튼 컨포넌트 Fix: url 수정, Refactor: 로고 라이브러리 사용X, Link사용
  client/src/App.js
  client/src/_reducers/userReducer.js
  client/src/components/Layout/Logo.js
  client/src/components/Layout/MobileNavMenu.js
  client/src/components/RecentProductsList.js
  client/src/components/UI/Button.js
  client/src/pages/Auth/Login.js
  client/src/pages/Auth/Register.js
  client/src/pages/Product/Detail.js
  client/src/pages/Product/DetailSlide.js
  client/src/pages/Product/Product.js
  client/src/styles/AddProduct.module.css
  client/src/styles/Button.module.css
  client/src/styles/Home.module.css
  client/src/styles/Login.module.css
  client/src/styles/Logo.module.css
  client/src/styles/Product.module.css
  client/src/styles/RecentProductsList.module.css
  client/src/styles/Register.module.css
Labels: 🌈 Frontend, 🐞 Fix, 🎨 Design, 🔨 Refactor, ✨ Feat

#113 Feat: 판매자정보 및 상품내용 토글 기능
  client/src/components/RecentProductsList.js
  client/src/components/UI/Modal.js
  client/src/pages/AddProduct/AddProduct.js
  client/src/pages/Home/Home.js
  client/src/pages/Home/HomeSlide.js
  client/src/pages/Product/Detail.js
  client/src/pages/Product/DetailSlide.js
  client/src/pages/Product/Product.js
  client/src/pages/Product/ProductInformation.js
  client/src/pages/Product/ProductStore.js
  client/src/styles/Detail.module.css
  client/src/styles/DetailSlide.module.css
  client/src/styles/Modal.module.css
Labels: 🌈 Frontend, 🐞 Fix, 🎨 Design, ✨ Feat

#114 Feat: loading spinner 생성
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/Layout/DesktopNavMenu.js
  client/src/components/RecentProductsList.js
  client/src/components/UI/Loading.js
  client/src/pages/AddProduct/AddProduct.js
  client/src/pages/Auth/Register.js
  client/src/pages/Home/HomeSlide.js
  client/src/pages/Product/DetailSlide.js
  client/src/styles/AddProduct.module.css
  client/src/styles/Header.module.css
  client/src/styles/Home.module.css
  client/src/styles/Loading.module.css
Labels: 🌈 Frontend, 🐞 Fix, 🎨 Design, ✨ Feat

#115 Feat: 페이지이동시 화면 최상단으로 스크롤
  client/src/App.js
  client/src/components/Layout/Header.js
  client/src/components/RecentProductsList.js
  client/src/components/UI/Loading.js
  client/src/components/UI/ScrollTop.js
  client/src/styles/RecentProductsList.module.css
Labels: 🌈 Frontend, 🐞 Fix, 🎨 Design, ✨ Feat

#116 Design: 상세페이지 버튼 디자인 변경
  client/src/pages/Product/Detail.js
  client/src/styles/Detail.module.css
Labels: 🌈 Frontend, 🎨 Design

#117 Merge: client -> dev
  client/.env.development.local.example
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/_actions/productAction.js
  client/src/_actions/userAction.js
  client/src/_reducers/productReducer.js
  client/src/_reducers/userReducer.js
  client/src/api/common.js
  client/src/components/Layout/DesktopNavMenu.js
  client/src/components/Layout/DropdownMenu.js
  client/src/components/Layout/Header.js
  client/src/components/Layout/Logo.js
  client/src/components/Layout/MobileNavMenu.js
  client/src/components/Layout/MyWallet.js
  client/src/components/Layout/UserAuth.js
  client/src/components/Layout/UserSection.js
  client/src/components/RecentProductsList.js
  client/src/components/UI/Button.js
  client/src/components/UI/Loading.js
  client/src/components/UI/Modal.js
  client/src/components/UI/Paging.js
  client/src/components/UI/ScrollTop.js
  client/src/index.js
  client/src/pages/AddProduct/AddProduct.js
  client/src/pages/Auth/Login.js
  client/src/pages/Auth/Register.js
  client/src/pages/Home/Home.js
  client/src/pages/Home/HomeSlide.js
  client/src/pages/Product/Detail.js
  client/src/pages/Product/DetailSlide.js
  client/src/pages/Product/Product.js
  client/src/pages/Product/ProductCard.js
  client/src/pages/Product/ProductInformation.js
  client/src/pages/Product/ProductStore.js
  client/src/styles/AddProduct.module.css
  client/src/styles/Button.module.css
  client/src/styles/Detail.module.css
  client/src/styles/DetailSlide.module.css
  client/src/styles/Header.module.css
  client/src/styles/Home.module.css
  client/src/styles/Loading.module.css
  client/src/styles/Login.module.css
  client/src/styles/Logo.module.css
  client/src/styles/Modal.module.css
  client/src/styles/Product.module.css
  client/src/styles/RecentProductsList.module.css
  client/src/styles/Register.module.css
  client/src/styles/UserAuth.module.css
Labels: 🌈 Frontend, 🔀 Merge

#119 Merge: server -> dev
  server/config/index.js
  server/config/passport.js
  server/controllers/productController.js
  server/loaders/containerObject.js
  server/loaders/dependencyConvert.js
  server/loaders/dependencyInjector.js
  server/loaders/index.js
  server/loaders/sequelize.js
  server/middlewares/validation.js
  server/models/index.js
  server/models/product.js
  server/routes/product.js
  server/seeders/20230604184326-product.js
  server/services/product.js
  server/test/products.json
  server/utils/ApiError.js
  server/utils/dataParsers.js
  server/utils/generalError.js
  server/utils/index.js
  server/utils/parse.js
Labels: 📬 API, 🔀 Merge

#118 Merge: client -> dev
  client/src/_actions/userAction.js
  client/src/components/Layout/DesktopNavMenu.js
  client/src/components/Layout/MyWallet.js
  client/src/components/Layout/UserSection.js
  client/src/index.js
Labels: 🌈 Frontend, 🔀 Merge

#120 Merge: contract -> dev
  contract/contracts/Platform.sol
  contract/contracts/SafeTxn.sol
  contract/contracts/interface/IEscrow.sol
  contract/contracts/interface/ISafeTxn.sol
  contract/package-lock.json
Labels: 📬 API, 🔀 Merge

#124 Feat: 내정보 컴포넌트 생성
  client/src/App.js
  client/src/components/Layout/UserSection.js
  client/src/pages/User/UserAddProduct.js
  client/src/pages/User/UserInfo.js
  client/src/pages/User/UserPurchaseProduct.js
  client/src/pages/User/UserWishList.js
  client/src/styles/UserInfo.module.css
Labels: 🌈 Frontend, 🎨 Design, ✨ Feat

#128 Rename: chatLog, chatRoom 모델 속성 이름 수정
  server/controllers/chatController.js
  server/models/chatLog.js
  server/models/chatRoom.js
Labels: 📬 API, 🐞 Fix, ✨ Feat

#129 Design: 헤더 디자인 변경
  client/src/App.js
  client/src/components/Layout/MyWallet.js
  client/src/components/Layout/UserSection.js
  client/src/components/RecentProductsList.js
  client/src/pages/Home/HomeSlide.js
  client/src/pages/Product/Detail.js
  client/src/pages/User/UserInfo.js
  client/src/styles/HomeSlide.module.css
  client/src/styles/RecentProductsList.module.css
  client/src/styles/UserInfo.module.css
Labels: 🌈 Frontend, 🐞 Fix, 🎨 Design, 🔀 Merge, ✨ Feat

#132 Fix: 드롭다운메뉴에 있는 내지갑 userSection에 표시
  client/src/components/Layout/Header.js
  client/src/components/Layout/Logo.js
  client/src/components/Layout/MyWallet.js
  client/src/components/Layout/UserSection.js
  client/src/components/User/Exchange.js
  client/src/pages/AddProduct/AddProduct.js
  client/src/pages/User/OnSaleProduct.js
  client/src/pages/User/PurchasedProduct.js
  client/src/pages/User/ReservedProduct.js
  client/src/pages/User/UserInfo.js
  client/src/pages/User/UserPurchaseProduct.js
  client/src/pages/User/WishList.js
  client/src/styles/AddProduct.module.css
  client/src/styles/Exchange.module.css
  client/src/styles/Header.module.css
Labels: 🌈 Frontend, 🐞 Fix, 🎨 Design, ✨ Feat

#133 Feat: Exchange Modal 라이브러리 사용 및 Exchange handle함수 추가
  client/src/components/Layout/MyWallet.js
  client/src/components/Layout/UserSection.js
  client/src/components/User/Exchange.js
  client/src/pages/User/ReservedProduct.js
  client/src/styles/ReservedProduct.module.css
  client/src/styles/UserInfo.module.css
Labels: 🌈 Frontend, 🐞 Fix, 🎨 Design, 🔀 Merge, ✨ Feat

#135 Feat: status에따라 최근상품표시 변경
  client/package-lock.json
  client/package.json
  client/src/components/Layout/Logo.js
  client/src/components/Layout/UserSection.js
  client/src/components/RecentProductsList.js
  client/src/index.js
  client/src/pages/AddProduct/AddProduct.js
  client/src/pages/Auth/Login.js
  client/src/pages/Auth/Register.js
  client/src/pages/Home/Home.js
  client/src/pages/Product/Detail.js
  client/src/styles/AddProduct.module.css
  client/src/styles/Detail.module.css
  client/src/styles/Home.module.css
  client/src/styles/Login.module.css
  client/src/styles/RecentProductsList.module.css
Labels: 🌈 Frontend, 🐞 Fix, 🎨 Design, 🔀 Merge, ✨ Feat

#136 Merge: contract -> dev
  contract/contracts/CommonFnWrapper.sol
  contract/contracts/PandaToken.sol
  contract/contracts/Platform.sol
  contract/contracts/SafeTxn.sol
  contract/contracts/interface/ISafeTxn.sol
Labels: 📬 API, 🔀 Merge

#137 Merge: server -> dev
  server/app.js
  server/controllers/chatController.js
  server/controllers/index.js
  server/controllers/productController.js
  server/loaders/dependencyConvert.js
  server/loaders/sequelize.js
  server/loaders/socket.js
  server/middlewares/isAuth.js
  server/models/chatLog.js
  server/models/chatRoom.js
  server/models/index.js
  server/package-lock.json
  server/package.json
  server/routes/chat.js
  server/routes/index.js
  server/routes/product.js
  server/services/chat.js
  server/services/index.js
  server/services/product.js
  server/utils/dataParsers.js
  server/utils/index.js
  server/utils/socketHandler.js
Labels: 📬 API, 🔀 Merge

#138 Merge: server -> dev
  server/controllers/productController.js
  server/loaders/express.js
  server/middlewares/secure.js
  server/package-lock.json
  server/package.json
  server/routes/product.js
  server/services/product.js
  server/utils/dataParsers.js
Labels: 📬 API, 🔀 Merge

#140 Rename: 파일 폴더화로 인한 이동
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/common/Alert.js
  client/src/components/common/Button.js
  client/src/components/common/ContractLoading.js
  client/src/components/common/ContractModal.js
  client/src/components/common/Loading.js
  client/src/components/common/Modal.js
  client/src/components/common/Paging.js
  client/src/components/common/ScrollTop.js
  client/src/components/headers/DesktopNavMenu.js
  client/src/components/headers/DropdownMenu.js
  client/src/components/headers/Exchange.js
  client/src/components/headers/Header.js
  client/src/components/headers/Logo.js
  client/src/components/headers/MobileNavMenu.js
  client/src/components/headers/MyWallet.js
  client/src/components/headers/UserAuth.js
  client/src/components/headers/UserMenu.js
  client/src/components/product/RecentProducts.js
  client/src/pages/AddProduct/AddProduct.js
  client/src/pages/Auth/Login.js
  client/src/pages/Auth/Register.js
  client/src/pages/Chat/Chat.js
  client/src/pages/Home/Home.js
  client/src/pages/Home/HomeSlide.js
  client/src/pages/Product/Detail.js
  client/src/pages/Product/DetailSlide.js
  client/src/pages/Product/Product.js
  client/src/pages/Product/ProductCard.js
  client/src/pages/User/ReservedProduct.js
  client/src/pages/User/UserInfo.js
  client/src/styles/UserSection.module.css
  client/src/styles/addProduct/AddProduct.module.css
  client/src/styles/auth/Login.module.css
  client/src/styles/auth/Register.module.css
  client/src/styles/chat/Chat.module.css
  client/src/styles/common/Button.module.css
  client/src/styles/common/ContractModal.module.css
  client/src/styles/common/Loading.module.css
  client/src/styles/common/Modal.module.css
  client/src/styles/headers/DropdownMenu.module.css
  client/src/styles/headers/Exchange.module.css
  client/src/styles/headers/Header.module.css
  client/src/styles/headers/Logo.module.css
  client/src/styles/headers/UserAuth.module.css
  client/src/styles/headers/UserMenu.module.css
  client/src/styles/home/Home.module.css
  client/src/styles/home/HomeSlide.module.css
  client/src/styles/product/Detail.module.css
  client/src/styles/product/DetailSlide.module.css
  client/src/styles/product/Product.module.css
  client/src/styles/product/ProductCard.module.css
  client/src/styles/product/RecentProducts.module.css
  client/src/styles/user/ReservedProduct.module.css
  client/src/styles/user/UserInfo.module.css
Labels: 🌈 Frontend, 🐞 Fix, ✨ Feat
