Repository legm0310/SafeTransactionPlatform, pull requests merged in 2023-10, with the labels that each got.

#176 Merge: 병합 충돌 해결
  client/src/_actions/chatAction.js
  client/src/_actions/type.js
  client/src/_reducers/chatReducer.js
  client/src/pages/Home/Home.js
  client/src/pages/User/UserInfo.js
Labels: 🌈 Frontend, 🐞 Fix

#177 Fix: 제품상세 무한로딩 해결
  client/src/_actions/productAction.js
  client/src/_reducers/userReducer.js
  client/src/index.css
  client/src/pages/Product/Product.js
  client/src/styles/headers/Header.module.css
  client/src/styles/product/Product.module.css
  client/src/styles/product/ProductCard.module.css
Labels: 🌈 Frontend, 🐞 Fix, 🎨 Design

#178 Feat: 제품 상세 페이지 기능 추가
  client/src/components/detailProduct/ProductInformation.js
  client/src/components/detailProduct/ProductStore.js
  client/src/styles/product/Detail.module.css
Labels: 🌈 Frontend, 🎨 Design, ✨ Feat

#179 Remove: wishList 모델 삭제
  server/controllers/userController.js
  server/models/wishList.js
  server/services/product.js
Labels: 📬 API, 🐞 Fix, ✨ Feat

#180 Fix: 키 오류 제거
  client/src/components/common/Modal.js
  client/src/components/headers/MyWallet.js
  client/src/components/user/WishList.js
  client/src/styles/headers/MyWallet.module.css
Labels: 🌈 Frontend, 🐞 Fix, 🎨 Design, 🔀 Merge

#181 찜목록 버그 수정 및 지갑 UI 개선 및 Footer 생성
  client/src/App.css
  client/src/App.js
  client/src/components/Footer/Footer.js
  client/src/components/headers/MyWallet.js
  client/src/components/product/ProductCard.js
  client/src/components/product/RecentProducts.js
  client/src/components/user/ReservedProduct.js
  client/src/components/user/WishItem.js
  client/src/components/user/WishList.js
  client/src/index.css
  client/src/pages/Product/Product.js
  client/src/styles/Footer/Footer.module.css
  client/src/styles/headers/Header.module.css
  client/src/styles/headers/MyWallet.module.css
  client/src/styles/product/Product.module.css
  client/src/styles/product/ProductCard.module.css
  client/src/styles/product/RecentProducts.module.css
  client/src/styles/user/OnSaleProduct.module.css
  client/src/styles/user/PurchasedProduct.module.css
  client/src/styles/user/ReservedProduct.module.css
  client/src/styles/user/UserInfo.module.css
  client/src/styles/user/WishList.module.css
Labels: 🌈 Frontend, 🐞 Fix, 🎨 Design, 🔀 Merge, ✨ Feat

#182 구매하기버튼 눌렀을 시 스낵바 미완성으로 주석처리
  client/src/components/chat/ChatRoom.js
  client/src/components/detailProduct/ProductSellor.js
  client/src/pages/DetailProduct/Detail.js
  client/src/styles/addProduct/AddProduct.module.css
  client/src/styles/chat/Chat.module.css
  client/src/styles/product/Detail.module.css
  client/src/styles/product/Product.module.css
  client/src/styles/user/UserInfo.module.css
Labels: 🌈 Frontend, 🎨 Design

#184 Refactor: getUser함수 변경
  server/controllers/userController.js
  server/routes/user.js
  server/services/auth.js
  server/services/user.js
Labels: 📬 API, 🔨 Refactor

#185 Design: 채팅방 UI 개선
  client/src/components/Footer/Footer.js
  client/src/components/chat/ChatRoom.js
  client/src/pages/DetailProduct/Detail.js
  client/src/styles/Footer/Footer.module.css
  client/src/styles/chat/Chat.module.css
  client/src/styles/product/Detail.module.css
Labels: 🌈 Frontend, 🎨 Design, ✨ Feat

#186 Feat: UserInfo 프로필 내용 추가
  client/src/App.js
  client/src/_actions/type.js
  client/src/_actions/userAction.js
  client/src/_reducers/userReducer.js
  client/src/components/headers/UserMenu.js
  client/src/pages/User/UserInfo.js
  client/src/styles/user/UserInfo.module.css
Labels: 🌈 Frontend, 🎨 Design, ✨ Feat

#187 채팅방 UI 개선 및 배너 추가
  client/src/App.js
  client/src/components/Banner/Banner.js
  client/src/components/Home/HomeSlide.js
  client/src/components/chat/Chats.js
  client/src/components/headers/Header.js
  client/src/pages/User/UserInfo.js
  client/src/styles/banner/Banner.module.css
  client/src/styles/chat/Chat.module.css
  client/src/styles/home/Home.module.css
  client/src/styles/home/HomeSlide.module.css
  client/src/styles/product/ProductCard.module.css
  client/src/styles/product/RecentProducts.module.css
  client/src/styles/user/UserInfo.module.css
Labels: 🌈 Frontend, 🎨 Design, 🔀 Merge, ✨ Feat

#188 Feat: user_name 및 introduce 수정 기능 추가
  server/controllers/userController.js
  server/loaders/sequelize.js
  server/models/user.js
  server/routes/user.js
  server/services/user.js
Labels: 📬 API, ✨ Feat

#189 Feat: User Name/Introduce 수정 API 추가
  client/src/_actions/type.js
  client/src/_actions/userAction.js
  client/src/_reducers/userReducer.js
  client/src/components/user/UserProfile.js
  client/src/components/user/WishItem.js
  client/src/pages/User/UserInfo.js
  client/src/styles/user/UserInfo.module.css
Labels: 🌈 Frontend, 🎨 Design, 🔨 Refactor, ✨ Feat

#191 메인홈, 내정보프로필, 배너 UI 개선
  client/src/App.js
  client/src/assets/bannerImg1.png
  client/src/assets/bannerImg2.png
  client/src/assets/bannerImg3.png
  client/src/assets/google.png
  client/src/assets/kakao.png
  client/src/assets/mainImg.png
  client/src/assets/pandaImg1.jpeg
  client/src/assets/pandaImg2.png
  client/src/assets/pandaImg3.png
  client/src/assets/pandaImg4.png
  client/src/assets/pandaImg5.png
  client/src/assets/test.jpg
  client/src/assets/testImg.png
  client/src/components/Banner/Banner.js
  client/src/components/Detail/DetailSlide.js
  client/src/components/Detail/ProductInformation.js
  client/src/components/Detail/ProductSellor.js
  client/src/components/Home/HomeSlide.js
  client/src/components/chat/Chats.js
  client/src/components/headers/Header.js
  client/src/components/user/UserProfile.js
  client/src/components/user/WishItem.js
  client/src/pages/Chat/Chat.js
  client/src/pages/Detail/Detail.js
  client/src/pages/Home/Home.js
  client/src/pages/Product/Product.js
  client/src/pages/User/UserInfo.js
  client/src/styles/Footer/Footer.module.css
  client/src/styles/banner/Banner.module.css
  client/src/styles/chat/Chat.module.css
  client/src/styles/detail/Detail.module.css
  client/src/styles/detail/DetailSlide.module.css
  client/src/styles/home/Home.module.css
  client/src/styles/home/HomeSlide.module.css
  client/src/styles/product/RecentProducts.module.css
  client/src/styles/user/UserInfo.module.css
Labels: 🌈 Frontend, 🐞 Fix, 🎨 Design, 🔀 Merge

#192 Refactor: 유저 이름, 소개글 수정 updateUser 함수 하나로 통일
  client/src/_actions/type.js
  client/src/_actions/userAction.js
  client/src/_reducers/userReducer.js
  client/src/components/Chat/ChatRoom.js
  client/src/components/Chat/Chats.js
  client/src/components/Chat/Message.js
  client/src/components/Chat/Search.js
  client/src/components/Chat/Sidebar.js
  client/src/components/Headers/DesktopNavMenu.js
  client/src/components/Headers/DropdownMenu.js
  client/src/components/Headers/Exchange.js
  client/src/components/Headers/Header.js
  client/src/components/Headers/Logo.js
  client/src/components/Headers/MobileNavMenu.js
  client/src/components/Headers/MyWallet.js
  client/src/components/Headers/UserAuth.js
  client/src/components/Headers/UserMenu.js
  client/src/components/Product/CategoryBar.js
  client/src/components/Product/ProductCard.js
  client/src/components/Product/RecentProducts.js
  client/src/components/User/PurchasedProduct.js
  client/src/components/User/ReservedProduct.js
  client/src/components/User/SaleItem.js
  client/src/components/User/SaleList.js
  client/src/components/User/UserProfile.js
  client/src/components/User/WishItem.js
  client/src/components/User/WishList.js
Labels: 🌈 Frontend, 🐞 Fix, 🎨 Design, 🔨 Refactor

#193 Refactor: 유저 이름, 소개글 수정 updateUser 함수 하나로 통일
  server/controllers/userController.js
  server/routes/user.js
  server/services/user.js
Labels: 📬 API, 🔨 Refactor

#194 Refactor: 리덕스 스토어 리팩토링
  client/src/_reducers/userReducer.js
  client/src/components/Headers/UserMenu.js
  client/src/components/User/ReservedProduct.js
  client/src/components/User/UserProfile.js
  client/src/styles/user/UserInfo.module.css
Labels: 🌈 Frontend, 🐞 Fix, 🎨 Design, 🔨 Refactor, ⚙ Chore

#195 Rename: updateUser로 API 이름 변경
  server/controllers/userController.js
  server/routes/user.js
  server/services/user.js
Labels: 📬 API

#196 Feat: manual 페이지 추가
  client/src/App.js
  client/src/assets/manual/manualImage01.png
  client/src/assets/manual/manualImage02.png
  client/src/assets/manual/manualImage03.png
  client/src/assets/manual/manualImage04.png
  client/src/assets/manual/manualImage05.png
  client/src/assets/manual/manualImage06.png
  client/src/assets/manual/manualImage07.png
  client/src/assets/manual/manualImage08.png
  client/src/assets/manual/manualImage09.png
  client/src/assets/manual/manualImage10.png
  client/src/assets/manual/manualImage11.png
  client/src/assets/manual/manualImage12.png
  client/src/assets/manual/manualImage13.png
  client/src/assets/manual/manualImage14.png
  client/src/assets/manual/manualImage15.png
  client/src/assets/manual/manualMainImg.png
  client/src/components/Manual/Manual.js
  client/src/styles/manual/Manual.module.css
Labels: 🌈 Frontend, 🎨 Design, ✨ Feat

#197 배너 슬라이드 UI 개선, Footer UI 개선
  client/src/components/Banner/Banner.js
  client/src/components/Footer/Footer.js
  client/src/components/Home/HomeSlide.js
  client/src/styles/Footer/Footer.module.css
  client/src/styles/banner/Banner.module.css
Labels: 🌈 Frontend, 🐞 Fix, 🎨 Design, 🔀 Merge

#198 Feat: 프로필로 가는 링크 사진 포함
  client/src/components/Detail/ProductSellor.js
  client/src/components/Footer/Footer.js
  client/src/components/User/UserProfile.js
  client/src/pages/Detail/Detail.js
  client/src/styles/Footer/Footer.module.css
Labels: 🌈 Frontend, 🐞 Fix, ✨ Feat, ⚙ Chore

#199 Design: 홈슬라이드 화살표 위치 조정
  client/src/components/Home/HomeSlide.js
Labels: 🌈 Frontend, 🎨 Design

#200 Design: 글자 위치 상하 조절
  client/src/components/Footer/Footer.js
Labels: 🌈 Frontend, 🎨 Design

#201 Design: 홈슬라이드 dots 제거
  client/src/components/Home/HomeSlide.js
Labels: 🌈 Frontend, 🎨 Design

#202 Design: 반응형 제작 1260px, 980px, 500px
  client/src/components/Product/RecentProducts.js
  client/src/styles/home/Home.module.css
  client/src/styles/home/HomeSlide.module.css
  client/src/styles/product/RecentProducts.module.css
Labels: 🌈 Frontend, 🐞 Fix, 🎨 Design

#203 Feat: 메뉴얼 하단 링크 추가
  client/src/components/Manual/Manual.js
Labels: 🌈 Frontend, ✨ Feat

#208 Merge: server -> dev
  server/.env.development.example
  server/.env.example
  server/app.js
  server/config/index.js
  server/config/passport.js
  server/controllers/chatController.js
  server/controllers/index.js
  server/controllers/productController.js
  server/controllers/userController.js
  server/loaders/express.js
  server/loaders/sequelize.js
  server/loaders/socket.js
  server/middlewares/isAuth.js
  server/models/category.js
  server/models/chatLog.js
  server/models/chatParticipant.js
  server/models/chatRoom.js
  server/models/index.js
  server/models/product.js
  server/models/user.js
  server/models/wishList.js
  server/package-lock.json
  server/package.json
  server/routes/chat.js
  server/routes/index.js
  server/routes/user.js
  server/services/auth.js
  server/services/chat.js
  server/services/product.js
  server/services/socket.js
  server/services/user.js
  server/utils/dataParsers.js
  server/utils/socketHandler.js
Labels: 📬 API, 🔀 Merge

#211 Fix: 온보딩 이미지 변경
  client/src/assets/pandaImg2.png
  client/src/assets/pandaImg4.png
  client/src/assets/pandaImg6.png
Labels: 🌈 Frontend, 🐞 Fix, 🎨 Design

#212 Feat: 페이지네이션 구현
  client/src/components/Headers/DesktopNavMenu.js
  client/src/components/Headers/MobileNavMenu.js
  client/src/components/common/Paging.js
  client/src/pages/Product/Product.js
  client/src/styles/common/Paging.css
Labels: 🌈 Frontend, 🎨 Design, ✨ Feat

#214 Fix: 이미지 삭제 및 추가
  client/src/assets/onboard/pandaImg2.png
  client/src/assets/onboard/pandaImg3.png
  client/src/assets/onboard/pandaImg4.png
  client/src/assets/onboard/pandaImg5.png
  client/src/assets/onboard/pandaImg6.png
  client/src/assets/onboard/pandaImgChat.png
  client/src/assets/pandaImg1.jpeg
  client/src/assets/testImg1.png
Labels: 🌈 Frontend, 🐞 Fix

#215 Feat: 페이지네이션 스트링 쿼리 추가
  client/src/pages/Product/Product.js
Labels: 🌈 Frontend, ✨ Feat

#216 Feat: 연관 상품 컴포넌트 생성 및 기능 구현
  client/src/components/Detail/RelatedProduct.js
  client/src/pages/Detail/Detail.js
  client/src/styles/detail/Detail.module.css
Labels: 🌈 Frontend, ✨ Feat, 🏷 Rename

#217 Feat: 판매자의 내정보 구분
  client/src/components/Footer/Footer.js
  client/src/components/Headers/DesktopNavMenu.js
  client/src/components/Headers/Header.js
  client/src/pages/User/UserInfo.js
  client/src/styles/home/Home.module.css
  client/src/styles/product/ProductCard.module.css
  client/src/styles/product/RecentProducts.module.css
Labels: 🌈 Frontend, 🐞 Fix, 🎨 Design, 🔀 Merge, ✨ Feat

#221 Merge: pull request
  client/src/pages/Product/Product.js
  client/src/styles/home/Home.module.css
  client/src/styles/product/Product.module.css
  client/src/styles/product/ProductCard.module.css
  client/src/styles/product/RecentProducts.module.css
Labels: 🌈 Frontend, 🐞 Fix, 🎨 Design, 🔀 Merge

#223 Feat: getInitUser API 추가
  server/controllers/userController.js
  server/routes/user.js
  server/services/user.js
Labels: 📬 API, ✨ Feat

#224 Feat: 찜하기 버튼 전후 상태 변경 기능 추가
  client/src/components/Detail/ProductSellor.js
  client/src/components/Detail/RelatedProduct.js
  client/src/pages/Detail/Detail.js
  client/src/styles/detail/Detail.module.css
Labels: 🌈 Frontend, 🎨 Design, ✨ Feat

#225 Refactor: 헤더 반응형 슬라이드로 변경
  client/src/_reducers/userReducer.js
  client/src/components/Headers/DesktopNavMenu.js
  client/src/components/Headers/MobileNavMenu.js
  client/src/components/Headers/UserMenu.js
Labels: 🌈 Frontend, 🐞 Fix, 🔨 Refactor, 🔀 Merge, 📃 Docs

#226 Feat: card width 문제로 인한 삼항연산자 추가
  client/src/assets/mainImg.png
  client/src/components/Product/RecentProducts.js
  client/src/styles/home/Home.module.css
  client/src/styles/product/Product.module.css
  client/src/styles/product/ProductCard.module.css
  client/src/styles/product/RecentProducts.module.css
Labels: 🌈 Frontend, 🎨 Design, 🔀 Merge, ✨ Feat

#227 Feat: Login 시 채팅, 찜목록 개수 가져오기 추가
  client/src/_reducers/userReducer.js
  client/src/components/Detail/RelatedProduct.js
  client/src/components/User/WishItem.js
  client/src/pages/Auth/Login.js
  client/src/pages/Detail/Detail.js
Labels: 🌈 Frontend, 🐞 Fix, ✨ Feat

#228 Merge: client -> dev
  client/src/App.js
  client/src/_actions/chatAction.js
  client/src/_actions/type.js
  client/src/_actions/userAction.js
  client/src/_reducers/chatReducer.js
  client/src/_reducers/userReducer.js
  client/src/assets/mainImg.png
  client/src/assets/onboard/pandaImg2.png
  client/src/assets/onboard/pandaImg3.png
  client/src/assets/onboard/pandaImg4.png
  client/src/assets/onboard/pandaImg5.png
  client/src/assets/onboard/pandaImg6.png
  client/src/assets/onboard/pandaImgChat.png
  client/src/assets/pandaImg1.jpeg
  client/src/assets/pandaImg2.png
  client/src/assets/pandaImg4.png
  client/src/assets/testImg1.png
  client/src/components/Banner/Banner.js
  client/src/components/Chat/ChatRoom.js
  client/src/components/Detail/ProductSellor.js
  client/src/components/Detail/RelatedProduct.js
  client/src/components/Footer/Footer.js
  client/src/components/Headers/DesktopNavMenu.js
  client/src/components/Headers/Header.js
  client/src/components/Headers/MobileNavMenu.js
  client/src/components/Headers/UserAuth.js
  client/src/components/Headers/UserMenu.js
  client/src/components/Product/ProductCard.js
  client/src/components/Product/RecentProducts.js
  client/src/components/User/WishItem.js
  client/src/components/common/Paging.js
  client/src/hoc/auth.js
  client/src/pages/Auth/Login.js
  client/src/pages/Chat/Chat.js
  client/src/pages/Detail/Detail.js
  client/src/pages/Product/Product.js
  client/src/pages/User/UserInfo.js
  client/src/styles/Footer/Footer.module.css
  client/src/styles/banner/Banner.module.css
  client/src/styles/common/Paging.css
  client/src/styles/detail/Detail.module.css
  client/src/styles/headers/Logo.module.css
  client/src/styles/home/Home.module.css
  client/src/styles/home/HomeSlide.module.css
  client/src/styles/product/Product.module.css
  client/src/styles/product/ProductCard.module.css
  client/src/styles/product/RecentProducts.module.css
  client/src/styles/user/UserInfo.module.css
Labels: 🌈 Frontend, 🔀 Merge

#229 Merge: server -> dev
  server/.env.development.example
  server/controllers/productController.js
  server/controllers/userController.js
  server/routes/user.js
  server/services/product.js
  server/services/user.js
Labels: 📬 API, 🔀 Merge

#230 Merge: dev -> main
  client/src/App.js
  client/src/_actions/chatAction.js
  client/src/_actions/type.js
  client/src/_actions/userAction.js
  client/src/_reducers/chatReducer.js
  client/src/_reducers/userReducer.js
  client/src/assets/mainImg.png
  client/src/assets/onboard/pandaImg2.png
  client/src/assets/onboard/pandaImg3.png
  client/src/assets/onboard/pandaImg4.png
  client/src/assets/onboard/pandaImg5.png
  client/src/assets/onboard/pandaImg6.png
  client/src/assets/onboard/pandaImgChat.png
  client/src/assets/pandaImg1.jpeg
  client/src/assets/pandaImg2.png
  client/src/assets/pandaImg4.png
  client/src/assets/testImg1.png
  client/src/components/Banner/Banner.js
  client/src/components/Chat/ChatRoom.js
  client/src/components/Detail/ProductSellor.js
  client/src/components/Detail/RelatedProduct.js
  client/src/components/Footer/Footer.js
  client/src/components/Headers/DesktopNavMenu.js
  client/src/components/Headers/Header.js
  client/src/components/Headers/MobileNavMenu.js
  client/src/components/Headers/UserAuth.js
  client/src/components/Headers/UserMenu.js
  client/src/components/Product/ProductCard.js
  client/src/components/Product/RecentProducts.js
  client/src/components/User/WishItem.js
  client/src/components/common/Paging.js
  client/src/hoc/auth.js
  client/src/pages/Auth/Login.js
  client/src/pages/Chat/Chat.js
  client/src/pages/Detail/Detail.js
  client/src/pages/Product/Product.js
  client/src/pages/User/UserInfo.js
  client/src/styles/Footer/Footer.module.css
  client/src/styles/banner/Banner.module.css
  client/src/styles/common/Paging.css
  client/src/styles/detail/Detail.module.css
  client/src/styles/headers/Logo.module.css
  client/src/styles/home/Home.module.css
  client/src/styles/home/HomeSlide.module.css
  client/src/styles/product/Product.module.css
  client/src/styles/product/ProductCard.module.css
  client/src/styles/product/RecentProducts.module.css
  client/src/styles/user/UserInfo.module.css
  server/.env.development.example
  server/controllers/productController.js
  server/controllers/userController.js
  server/routes/user.js
  server/services/product.js
  server/services/user.js
Labels: 📬 API, 🌈 Frontend, 🔀 Merge

#231 Feat: Detail, UserProfile 기능 추가
  client/src/components/User/UserProfile.js
  client/src/pages/Detail/Detail.js
Labels: 🌈 Frontend, ✨ Feat

#232 Design: UI 개선
  client/src/assets/onboard/bannerMainImg.png
  client/src/components/Banner/Banner.js
  client/src/styles/banner/Banner.module.css
Labels: 🌈 Frontend, 🎨 Design

#233 Design: 온보드 UI 개선
  client/src/assets/onboard/pandaImg4.png
  client/src/assets/onboard/pandaImgChat.png
  client/src/components/Banner/Banner.js
  client/src/styles/banner/Banner.module.css
Labels: 🌈 Frontend, 🎨 Design

#234 Design: 구매페이지 반응형 제작
  client/src/components/Footer/Footer.js
  client/src/components/Headers/DesktopNavMenu.js
  client/src/components/Headers/Header.js
  client/src/components/Headers/Logo.js
  client/src/components/Headers/MobileNavMenu.js
  client/src/components/Headers/UserMenu.js
  client/src/components/Product/CategoryBar.js
  client/src/components/Product/ProductCard.js
  client/src/pages/Auth/Login.js
  client/src/pages/Product/Product.js
  client/src/styles/auth/Login.module.css
  client/src/styles/auth/Register.module.css
  client/src/styles/home/Home.module.css
  client/src/styles/home/HomeSlide.module.css
  client/src/styles/product/Product.module.css
  client/src/styles/product/ProductCard.module.css
  client/src/styles/product/ReactMinimalSideNavigation.css
  client/src/styles/product/RecentProducts.module.css
Labels: 🌈 Frontend, 🐞 Fix, 🎨 Design, 📃 Docs

#235 Feat: 상세페이지 연관상품 슬라이드 기능
  client/package-lock.json
  client/package.json
  client/src/components/Detail/RelateProductSlide.js
  client/src/components/Detail/RelatedProduct.js
  client/src/pages/Detail/Detail.js
  client/src/pages/Product/Product.js
  client/src/styles/detail/Detail.module.css
  client/src/styles/detail/RelateProductSlide.module.css
  client/src/styles/detail/styles.css
  client/src/styles/product/Product.module.css
Labels: 🌈 Frontend, 🐞 Fix, 🎨 Design, 🔀 Merge, ✨ Feat

#236 Design: 판매진행상품 UI 개선
  client/src/components/User/ReservedProduct.js
  client/src/styles/user/ReservedProduct.module.css
  client/src/styles/user/WishList.module.css
Labels: 🌈 Frontend, 🎨 Design

#237 Feat: getProducts API에 제품 찜 개수 포함
  server/services/product.js
  server/services/user.js
Labels: 📬 API, ✨ Feat, ⚙ Chore

#240 Design: 디테일페이지 반응형, 사진크기 조정
  client/src/components/User/UserProfile.js
  client/src/index.css
  client/src/pages/Detail/Detail.js
  client/src/styles/detail/Detail.module.css
  client/src/styles/detail/DetailSlide.module.css
  client/src/styles/user/UserInfo.module.css
Labels: 🌈 Frontend, 🎨 Design, 📃 Docs

#241 Feat: Detail 페이지의 구매하기 버튼 Product Status에 따른 조건부 랜더링 추가
  client/src/_reducers/chatReducer.js
  client/src/pages/Detail/Detail.js
  client/src/styles/detail/Detail.module.css
Labels: 🌈 Frontend, 🎨 Design, ✨ Feat

#242 Feat: 구매진행중 영수증 파일 생성
  client/src/components/Home/HomeSlide.js
  client/src/components/Receipt/DepositReceipt.js
  client/src/components/Receipt/ReleaseReceipt.js
  client/src/components/User/PurchasedList.js
Labels: 🌈 Frontend, 🐞 Fix, 🎨 Design, 🔀 Merge, ✨ Feat, 🏷 Rename

#243 Feat: 채팅방의 상대방 userName 누르면 상대방 프로필 이동 기능 추가
  client/src/components/Chat/ChatRoom.js
  client/src/components/User/UserProfile.js
  client/src/styles/user/UserInfo.module.css
Labels: 🌈 Frontend, 🎨 Design, ✨ Feat

#245 Fix: 메세지 읽음 처리 로직 수정
  client/src/_reducers/chatReducer.js
  client/src/components/Chat/Chats.js
  client/src/components/Receipt/DepositReceipt.js
  client/src/components/User/PurchasedList.js
  client/src/components/User/ReservedList.js
  client/src/styles/chat/Chat.module.css
  client/src/styles/user/ReservedList.module.css
Labels: 🌈 Frontend, 🐞 Fix, 🎨 Design, 🔀 Merge, ✨ Feat

#249 Fix: 타유저 상세정보에서 내 프로필로 갔을 때 리렌더링 되지 않던 오류 해결
  client/src/components/Chat/Search.js
  client/src/components/Chat/Sidebar.js
  client/src/components/Headers/DesktopNavMenu.js
  client/src/components/User/UserProfile.js
  client/src/components/User/WishItem.js
  client/src/styles/chat/Chat.module.css
  client/src/styles/headers/Header.module.css
Labels: 🌈 Frontend, 🐞 Fix, 🎨 Design, ✨ Feat

#250 Design: slick-dots UI 개선
  client/src/components/Detail/DetailSlide.js
  client/src/pages/AddProduct/AddProduct.js
  client/src/styles/addProduct/AddProduct.module.css
  client/src/styles/detail/Detail.module.css
Labels: 🌈 Frontend, 🐞 Fix, 🎨 Design, 🔀 Merge

#251 Feat: activeMenu 기능 추가
  client/src/components/Headers/MyWallet.js
  client/src/components/Receipt/ReleaseReceipt.js
  client/src/components/Receipt/TransacDetailReceipt.js
  client/src/components/Receipt/TransacInfo.js
  client/src/components/User/PurchasedList.js
  client/src/pages/User/UserInfo.js
  client/src/styles/receipt/ReleaseReceipt.module.css
  client/src/styles/receipt/TransactionDetailReceipt.module.css
Labels: 🌈 Frontend, 🐞 Fix, 🎨 Design, 🔀 Merge, ✨ Feat

#252 Feat: getProductById, hasWishList 추가
  server/services/product.js
  server/services/user.js
Labels: 📬 API, ✨ Feat, 🏷 Rename

#253 Fix: WishList 페이지 wishCount 및 ActiveWish 오류 해결
  client/src/_reducers/userReducer.js
  client/src/pages/Detail/Detail.js
Labels: 🌈 Frontend, 🐞 Fix

#254 Design: 찜목록 반응형
  client/src/components/Headers/UserMenu.js
  client/src/components/User/PurchasedList.js
  client/src/components/User/ReservedList.js
  client/src/components/User/SaleList.js
  client/src/components/User/WishItem.js
  client/src/styles/user/PurchasedList.module.css
  client/src/styles/user/ReservedList.module.css
  client/src/styles/user/SaleList.module.css
  client/src/styles/user/UserInfo.module.css
  client/src/styles/user/WishList.module.css
Labels: 🌈 Frontend, 🎨 Design, 📃 Docs

#255 Feat: AddProduct 입력값 예외 처리
  client/src/_actions/productAction.js
  client/src/_actions/type.js
  client/src/_reducers/productReducer.js
  client/src/components/AddProduct/AddProduct.js
  client/src/components/Detail/DetailSlide.js
  client/src/pages/AddProduct/AddProduct.js
Labels: 🌈 Frontend, ✨ Feat

#257 Feat: 상품 카테고리 띄움
  client/src/components/Banner/Banner.js
  client/src/components/Detail/DetailSlide.js
  client/src/components/Footer/Footer.js
  client/src/components/User/WishItem.js
  client/src/index.css
  client/src/pages/AddProduct/AddProduct.js
  client/src/styles/Footer/Footer.module.css
  client/src/styles/addProduct/AddProduct.module.css
  client/src/styles/banner/Banner.module.css
  client/src/styles/home/Home.module.css
  client/src/styles/manual/Manual.module.css
  client/src/styles/receipt/ReleaseReceipt.module.css
  client/src/styles/receipt/TransactionDetailReceipt.module.css
  client/src/styles/user/WishList.module.css
Labels: 🌈 Frontend, 🐞 Fix, 🎨 Design, 🔀 Merge

#258 Feat: deleteProduct API 추가
  server/controllers/productController.js
  server/routes/product.js
  server/services/product.js
  server/utils/dataParsers.js
Labels: 🌈 Frontend, ✨ Feat

#259 Feat: 판매상품 컴포넌트 구현
  client/src/components/User/SaleList.js
  client/src/pages/User/UserInfo.js
Labels: 🌈 Frontend, 🐞 Fix, ✨ Feat

#260 Feat: 키 값 추가, Design: 내정보, 배너 UI 개선
  client/package-lock.json
  client/src/components/Banner/Banner.js
  client/src/components/Headers/DesktopNavMenu.js
  client/src/components/Headers/Logo.js
  client/src/components/Headers/MobileNavMenu.js
  client/src/components/Headers/UserAuth.js
  client/src/components/Headers/UserMenu.js
  client/src/components/User/SaleList.js
  client/src/components/User/WishItem.js
  client/src/config/customTheme.js
  client/src/pages/Auth/Login.js
  client/src/pages/Auth/Register.js
  client/src/styles/Footer/Footer.module.css
  client/src/styles/banner/Banner.module.css
  client/src/styles/chat/Chat.module.css
  client/src/styles/common/Button.module.css
  client/src/styles/notice/Notice.module.css
  client/src/styles/user/PurchasedList.module.css
  client/src/styles/user/ReservedList.module.css
  client/src/styles/user/SaleList.module.css
  client/src/styles/user/WishList.module.css
Labels: 🌈 Frontend, 🐞 Fix, 🎨 Design, 🔀 Merge, ✨ Feat

#261 Design: 배너페이지 반응형 추가
  client/package-lock.json
  client/src/components/Banner/Banner.js
  client/src/styles/banner/Banner.module.css
Labels: 🌈 Frontend, 🎨 Design

#262 Feat: 내정보 판매상품에 상품 상태 표시
  client/src/components/User/SaleList.js
  client/src/styles/user/SaleList.module.css
  client/src/styles/user/UserInfo.module.css
Labels: 🌈 Frontend, 🎨 Design, ✨ Feat

#263 Design: 메뉴얼 페이지 반응형
  client/src/styles/banner/Banner.module.css
  client/src/styles/manual/Manual.module.css
Labels: 🌈 Frontend, 🎨 Design

#264 Design: 이미지 사이즈 비율 조정(fill -> cover)
  client/src/components/Detail/ProductInformation.js
  client/src/pages/AddProduct/AddProduct.js
  client/src/pages/Detail/Detail.js
  client/src/styles/addProduct/AddProduct.module.css
  client/src/styles/detail/Detail.module.css
  client/src/styles/detail/DetailSlide.module.css
  client/src/styles/product/RecentProducts.module.css
  client/src/styles/user/SaleList.module.css
  client/src/styles/user/WishList.module.css
Labels: 🌈 Frontend, 🎨 Design, ✨ Feat

#266 Feat: 카카오, 구글 로그인 알림 추가
  client/src/pages/Auth/Login.js
Labels: 🌈 Frontend, ✨ Feat

#267 Design: 채팅방 반응형 제작
  client/src/components/Chat/ChatRoom.js
  client/src/styles/chat/Chat.module.css
Labels: 🌈 Frontend, 🎨 Design, 📃 Docs

#268 Feat: 구매확정 버튼 조건부 기능 추가
  client/src/components/Detail/DetailSlide.js
  client/src/components/Headers/UserMenu.js
  client/src/components/User/ReservedList.js
  client/src/components/User/WishItem.js
  client/src/pages/Home/Home.js
  client/src/styles/chat/Chat.module.css
  client/src/styles/headers/MyWallet.module.css
  client/src/styles/home/Home.module.css
  client/src/styles/product/ReactMinimalSideNavigation.css
  client/src/styles/user/ReservedList.module.css
  client/src/styles/user/UserInfo.module.css
Labels: 🌈 Frontend, 🐞 Fix, 🎨 Design, 🔀 Merge, ✨ Feat

#269 Feat: 배너 슬라이드 이미지 추가
  client/src/assets/onboard/pandaImg7.png
  client/src/components/Banner/Banner.js
Labels: 🌈 Frontend, ✨ Feat

#270 Design: 구매진행상품 UI 개선
  client/src/components/User/ReservedList.js
  client/src/styles/headers/MyWallet.module.css
  client/src/styles/user/ReservedList.module.css
Labels: 🌈 Frontend, 🎨 Design, 🔀 Merge

#271 Feat: 찜목록 상품 상태 표시
  client/src/components/User/PurchasedList.js
  client/src/components/User/WishItem.js
  client/src/styles/user/PurchasedList.module.css
  client/src/styles/user/ReservedList.module.css
  client/src/styles/user/UserInfo.module.css
  client/src/styles/user/WishList.module.css
Labels: 🌈 Frontend, 🔨 Refactor, ✨ Feat

#272 Feat: 배너 이미지 추가
  client/src/assets/homeBannerImg.png
  client/src/pages/Home/Home.js
  client/src/styles/home/Home.module.css
Labels: 🌈 Frontend, 🎨 Design, ✨ Feat

#277 Design: 구매완료상품 UI 개선
  client/src/components/User/PurchasedList.js
  client/src/styles/user/PurchasedList.module.css
  client/src/styles/user/ReservedList.module.css
  client/src/styles/user/SaleList.module.css
Labels: 🌈 Frontend, 🐞 Fix, 🎨 Design, 🔀 Merge

#278 Design: 구매하기 상품 반응형 수정
  client/src/styles/detail/DetailSlide.module.css
  client/src/styles/product/RecentProducts.module.css
Labels: 🌈 Frontend, 🎨 Design

#279 Merge: client -> dev
  client/src/_actions/productAction.js
  client/src/components/Receipt/TransacDetailReceipt.js
  client/src/components/User/PurchasedList.js
  client/src/components/User/ReservedList.js
  client/src/components/User/SaleList.js
  client/src/config/dappOptions.js
  client/src/styles/detail/DetailSlide.module.css
  client/src/styles/product/RecentProducts.module.css
  client/src/styles/user/PurchasedList.module.css
  client/src/styles/user/ReservedList.module.css
  client/src/styles/user/SaleList.module.css
Labels: 🌈 Frontend, 🔀 Merge

#280 Merge: server -> dev
  server/controllers/productController.js
  server/loaders/sequelize.js
  server/services/product.js
  server/services/user.js
  server/utils/dataParsers.js
Labels: 📬 API, 🔀 Merge

#281 Merge: contract -> dev
  contract/contracts/SafeTxn.sol
  contract/contracts/interface/IEscrow.sol
  contract/contracts/interface/ISafeTxn.sol
  contract/contracts/lib/Structs.sol
  contract/package-lock.json
  contract/package.json
Labels: 🔀 Merge

#282 Merge: dev -> main
  client/src/_actions/productAction.js
  client/src/components/Receipt/TransacDetailReceipt.js
  client/src/components/User/PurchasedList.js
  client/src/components/User/ReservedList.js
  client/src/components/User/SaleList.js
  client/src/config/dappOptions.js
  client/src/styles/detail/DetailSlide.module.css
  client/src/styles/product/RecentProducts.module.css
  client/src/styles/user/PurchasedList.module.css
  client/src/styles/user/ReservedList.module.css
  client/src/styles/user/SaleList.module.css
  contract/contracts/SafeTxn.sol
  contract/contracts/interface/IEscrow.sol
  contract/contracts/interface/ISafeTxn.sol
  contract/contracts/lib/Structs.sol
  contract/package-lock.json
  contract/package.json
  server/controllers/productController.js
  server/loaders/sequelize.js
  server/services/product.js
  server/services/user.js
  server/utils/dataParsers.js
Labels: 📬 API, 🌈 Frontend, 🔀 Merge

#283 Design: 연관상품 사진 크기 조절
  client/src/styles/detail/RelateProductSlide.module.css
Labels: 🌈 Frontend, 🎨 Design

#284 Design: 연관상품 사진 크기 수정
  client/src/styles/detail/RelateProductSlide.module.css
  client/src/styles/detail/styles.css
  client/src/styles/home/Home.module.css
  client/src/styles/product/Product.module.css
  client/src/styles/product/ProductCard.module.css
  client/src/styles/product/RecentProducts.module.css
  client/src/styles/user/PurchasedList.module.css
  client/src/styles/user/ReservedList.module.css
  client/src/styles/user/SaleList.module.css
  client/src/styles/user/WishList.module.css
Labels: 🌈 Frontend, 🎨 Design

#285 Fix: 트랜잭션 정보 삭제
  client/src/components/Receipt/DepositReceipt.js
  client/src/components/Receipt/ReleaseReceipt.js
  client/src/components/User/PurchasedList.js
  client/src/components/User/ReservedList.js
  client/src/styles/detail/styles.css
  client/src/styles/receipt/TransactionDetailReceipt.module.css
  client/src/styles/user/PurchasedList.module.css
  client/src/styles/user/SaleList.module.css
Labels: 🐞 Fix, 🎨 Design, 🔀 Merge

#286 Merge: client -> dev
  client/src/_actions/productAction.js
  client/src/_actions/userAction.js
  client/src/components/Headers/DesktopNavMenu.js
  client/src/components/Headers/Exchange.js
  client/src/components/Receipt/DepositReceipt.js
  client/src/components/Receipt/ReleaseReceipt.js
  client/src/components/Receipt/TransacDetailReceipt.js
  client/src/components/User/PurchasedList.js
  client/src/components/User/ReservedList.js
  client/src/components/User/SaleList.js
  client/src/pages/Detail/Detail.js
  client/src/styles/detail/RelateProductSlide.module.css
  client/src/styles/detail/styles.css
  client/src/styles/home/Home.module.css
  client/src/styles/product/Product.module.css
  client/src/styles/product/ProductCard.module.css
  client/src/styles/product/RecentProducts.module.css
  client/src/styles/receipt/TransactionDetailReceipt.module.css
  client/src/styles/user/PurchasedList.module.css
  client/src/styles/user/ReservedList.module.css
  client/src/styles/user/SaleList.module.css
  client/src/styles/user/WishList.module.css
  client/src/utils/abi.js
Labels: 🌈 Frontend, 🔀 Merge

#287 Merge: server -> dev
  server/controllers/productController.js
  server/services/product.js
Labels: 📬 API, 🔀 Merge

#289 Merge: dev -> main
  client/src/_actions/productAction.js
  client/src/_actions/userAction.js
  client/src/components/Headers/DesktopNavMenu.js
  client/src/components/Headers/Exchange.js
  client/src/components/Receipt/DepositReceipt.js
  client/src/components/Receipt/ReleaseReceipt.js
  client/src/components/Receipt/TransacDetailReceipt.js
  client/src/components/User/PurchasedList.js
  client/src/components/User/ReservedList.js
  client/src/components/User/SaleList.js
  client/src/pages/Detail/Detail.js
  client/src/styles/detail/RelateProductSlide.module.css
  client/src/styles/detail/styles.css
  client/src/styles/home/Home.module.css
  client/src/styles/product/Product.module.css
  client/src/styles/product/ProductCard.module.css
  client/src/styles/product/RecentProducts.module.css
  client/src/styles/receipt/TransactionDetailReceipt.module.css
  client/src/styles/user/PurchasedList.module.css
  client/src/styles/user/ReservedList.module.css
  client/src/styles/user/SaleList.module.css
  client/src/styles/user/WishList.module.css
  client/src/utils/abi.js
  contract/contracts/SafeTxn.sol
  contract/contracts/interface/ISafeTxn.sol
  server/controllers/productController.js
  server/services/product.js
Labels: 📬 API, 🌈 Frontend, 🔀 Merge

#290 Merge: client -> dev
  client/src/components/User/ReservedList.js
  client/src/styles/user/PurchasedList.module.css
Labels: 🌈 Frontend, 🔀 Merge

#291 Merge: dev -> main
  client/src/components/User/ReservedList.js
  client/src/styles/user/PurchasedList.module.css
Labels: 📬 API, 🌈 Frontend, 🔀 Merge

#292 Merge: client -> dev
  client/src/components/Receipt/DepositReceipt.js
  client/src/components/Receipt/ReleaseReceipt.js
  client/src/components/Receipt/TransacDetailReceipt.js
  client/src/components/User/PurchasedList.js
  client/src/components/User/ReservedList.js
  client/src/pages/Detail/Detail.js
  client/src/styles/user/PurchasedList.module.css
Labels: 🌈 Frontend, 🔀 Merge

#293 Merge: dev -> main
  client/src/components/Receipt/DepositReceipt.js
  client/src/components/Receipt/ReleaseReceipt.js
  client/src/components/Receipt/TransacDetailReceipt.js
  client/src/components/User/PurchasedList.js
  client/src/components/User/ReservedList.js
  client/src/pages/Detail/Detail.js
  client/src/styles/user/PurchasedList.module.css
Labels: 📬 API, 🌈 Frontend, 🔀 Merge
