Repository legm0310/SafeTransactionPlatform, pull requests merged in 2023-04, with the labels that each got.

#10 Merge : feat/client 병합
  .gitignore
  client/.gitignore
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.css
  client/src/App.js
  client/src/App.test.js
  client/src/components/AddProduct/AddProduct.js
  client/src/components/AddProduct/AddProduct.module.css
  client/src/components/Home/Home.js
  client/src/components/Home/Home.module.css
  client/src/components/Layout/DropdownMenu.js
  client/src/components/Layout/DropdownMenu.module.css
  client/src/components/Layout/Header.js
  client/src/components/Layout/Header.module.css
  client/src/components/Layout/Login.js
  client/src/components/Layout/Login.module.css
  client/src/components/Purchase/Purchase.js
  client/src/components/Purchase/Purchase.module.css
  client/src/components/Sale/Sale.js
  client/src/components/Sale/Sale.module.css
  client/src/components/UI/Modal.js
  client/src/components/UI/Modal.module.css
  client/src/index.css
  client/src/index.js
  client/src/reportWebVitals.js
Labels: 🌈 Frontend, 🔀 Merge

#11 Feat: Ul 추가 및 변경
  client/src/App.js
  client/src/assets/google.png
  client/src/assets/google.svg
  client/src/assets/kakao.png
  client/src/assets/kakao.svg
  client/src/components/Auth/Login.js
  client/src/components/Auth/Login.module.css
  client/src/components/Auth/Register.js
  client/src/components/Auth/Register.module.css
  client/src/components/Layout/Header.js
  client/src/components/Layout/Header.module.css
  client/src/components/Layout/Login.js
  client/src/components/Layout/Login.module.css
  client/src/components/Layout/UserAuth.js
  client/src/components/Layout/UserAuth.module.css
  client/src/components/UI/Modal.module.css
Labels: 🌈 Frontend, 🎨 Design, ✨ Feat

#12 Feat: 회원가입 및 로그인 로직 추가
  client/package-lock.json
  client/package.json
  client/src/_actions/type.js
  client/src/_actions/user_action.js
  client/src/_reducers/index.js
  client/src/_reducers/user_reducer.js
  client/src/components/AddProduct/AddProduct.js
  client/src/components/Auth/Login.js
  client/src/components/Auth/Register.js
  client/src/components/Auth/Register.module.css
  client/src/index.js
Labels: 🌈 Frontend, ✨ Feat

#13 Feat: 회원가입MVC, Database연결
  server/config/database.js
  server/controllers/index.js
  server/controllers/userController.js
  server/models/user.js
  server/routes/user.js
Labels: 📬 API, 🔨 Refactor, ✨ Feat

#14 Feat: app.js 라우터, db연결 추가
  server/.gitignore
  server/app.js
  server/package-lock.json
  server/package.json
Labels: 📬 API, ✨ Feat, ⚙ Chore

#15 Feat: 로그인 로직, user 모델 메서드
  server/app.js
  server/config/config.json
  server/config/database.js
  server/controllers/userController.js
  server/models/index.js
  server/models/user.js
Labels: 📬 API, 🔨 Refactor, ✨ Feat

#16 Feat: 카테고리 변경 및 상품 판매 폼 변경
  client/src/components/AddProduct/AddProduct.js
  client/src/components/AddProduct/AddProduct.module.css
  client/src/components/Layout/DropdownMenu.js
  client/src/components/Purchase/CategoryBox.js
  client/src/components/Purchase/CategoryBox.module.css
  client/src/components/Purchase/Purchase.js
  client/src/components/Purchase/Purchase.module.css
Labels: 🌈 Frontend, 🎨 Design, ✨ Feat

#17 Feat: 로그인 토큰 발급 구현
  server/app.js
  server/config/config.json
  server/controllers/userController.js
  server/models/index.js
  server/models/user.js
Labels: 📬 API, ✨ Feat, ⚙ Chore

#18 Feat: 상품카드리스트 js파일추가 및 상품등록한 값들을 상품카드리스트에 보내는 로직추가
  client/src/App.js
  client/src/components/AddProduct/AddProduct.js
  client/src/components/AddProduct/AddProduct.module.css
  client/src/components/Auth/Login.module.css
  client/src/components/Auth/Register.module.css
  client/src/components/Purchase/Purchase.js
  client/src/components/Purchase/Purchase.module.css
  client/src/components/Purchase/PurchaseList.js
  client/src/components/Purchase/PurchaseList.module.css
Labels: 🌈 Frontend, 🎨 Design, ✨ Feat

#20 Chore: .env 양식 파일
  server/.env.example
Labels: ⚙ Chore, 📃 Docs
