Repository legm0310/SafeTransactionPlatform, pull requests merged in 2023-05, with the labels that each got.

#22 Refactor: 로그인/회원가입 엔드포인트 URL 변경, Feat: 프록시 설정을 위한 setupProxy.js파일 생성
  client/src/App.js
  client/src/_actions/user_action.js
  client/src/components/AddProduct/AddProduct.js
  client/src/components/Auth/Register.js
  client/src/components/Home/Home.js
  client/src/components/Home/Home.module.css
  client/src/components/Layout/DropdownMenu.js
  client/src/components/Layout/DropdownMenu.module.css
  client/src/components/Layout/Header.js
  client/src/components/Layout/Header.module.css
  client/src/components/Purchase/DetailPurchase.js
  client/src/components/Purchase/DetailPurchase.module.css
  client/src/components/Purchase/Purchase.js
  client/src/components/Purchase/Purchase.module.css
  client/src/setupProxy.js
Labels: 🌈 Frontend, 🔨 Refactor, ✨ Feat

#23 Merge: client -> dev병합
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/_actions/type.js
  client/src/_actions/user_action.js
  client/src/_reducers/index.js
  client/src/_reducers/user_reducer.js
  client/src/assets/google.png
  client/src/assets/google.svg
  client/src/assets/kakao.png
  client/src/assets/kakao.svg
  client/src/components/AddProduct/AddProduct.js
  client/src/components/AddProduct/AddProduct.module.css
  client/src/components/Auth/Login.js
  client/src/components/Auth/Login.module.css
  client/src/components/Auth/Register.js
  client/src/components/Auth/Register.module.css
  client/src/components/Home/Home.js
  client/src/components/Home/Home.module.css
  client/src/components/Layout/DropdownMenu.js
  client/src/components/Layout/DropdownMenu.module.css
  client/src/components/Layout/Header.js
  client/src/components/Layout/Header.module.css
  client/src/components/Layout/Login.js
  client/src/components/Layout/Login.module.css
  client/src/components/Layout/UserAuth.js
  client/src/components/Layout/UserAuth.module.css
  client/src/components/Purchase/CategoryBox.js
  client/src/components/Purchase/CategoryBox.module.css
  client/src/components/Purchase/DetailPurchase.js
  client/src/components/Purchase/DetailPurchase.module.css
  client/src/components/Purchase/Purchase.js
  client/src/components/Purchase/Purchase.module.css
  client/src/components/Purchase/PurchaseList.js
  client/src/components/Purchase/PurchaseList.module.css
  client/src/components/UI/Modal.module.css
  client/src/index.js
  client/src/setupProxy.js
Labels: 🌈 Frontend, 🔀 Merge

#24 Merge: server->dev병합
  server/.env.example
  server/.gitignore
  server/app.js
  server/config/index.js
  server/controllers/authController.js
  server/controllers/index.js
  server/controllers/prodController.js
  server/loaders/dependencyInjector.js
  server/loaders/express.js
  server/loaders/index.js
  server/loaders/sequelize.js
  server/middlewares/index.js
  server/middlewares/isAuth.js
  server/models/chatContent.js
  server/models/chatRoom.js
  server/models/index.js
  server/models/product.js
  server/models/user.js
  server/package-lock.json
  server/package.json
  server/routes/auth.js
  server/routes/index.js
  server/routes/product.js
  server/services/auth.js
  server/services/index.js
  server/services/product.js
  server/utils/authentication.js
Labels: 📬 API, 🔀 Merge

#25 Feat: Product, chat 추가
  server/app.js
  server/config/passport.js
  server/controllers/authController.js
  server/loaders/containerObject.js
  server/loaders/dependencyInjector.js
  server/loaders/express.js
  server/loaders/index.js
  server/middlewares/isAuth.js
  server/models/chatContent.js
  server/models/chatRoom.js
  server/models/index.js
  server/models/product.js
  server/models/token.js
  server/models/user.js
  server/package-lock.json
  server/package.json
  server/routes/auth.js
  server/services/auth.js
  server/services/index.js
  server/services/product.js
  server/services/token.js
  server/services/user.js
  server/utils/ApiError.js
  server/utils/authentication.js
Labels: 📬 API, 🐞 Fix, 🔨 Refactor, ✨ Feat

#26 Comment: loader, routes, authController, authService
  server/app.js
  server/controllers/index.js
  server/loaders/dependencyInjector.js
  server/loaders/express.js
  server/loaders/index.js
  server/middlewares/isAuth.js
  server/models/product.js
  server/models/token.js
  server/models/user.js
  server/routes/auth.js
  server/routes/index.js
  server/routes/product.js
  server/services/auth.js
  server/services/token.js
Labels: 📬 API, 🔨 Refactor, ⚙ Chore

#27 Feat: 가격 input 숫자 입력시 콤마 자동생성, Design: CSS 변경, Refactor: className추가
  client/src/components/AddProduct/AddProduct.js
  client/src/components/AddProduct/AddProduct.module.css
  client/src/components/Layout/Header.module.css
  client/src/components/Purchase/Purchase.module.css
  client/src/components/Purchase/PurchaseList.js
  client/src/components/Purchase/PurchaseList.module.css
Labels: 🎨 Design, 🔨 Refactor, ✨ Feat

#29 Feat: logout, product
  server/.env.example
  server/config/index.js
  server/controllers/authController.js
  server/loaders/index.js
  server/models/index.js
  server/models/product.js
  server/models/user.js
  server/routes/auth.js
  server/services/auth.js
  server/services/token.js
Labels: 📬 API, ✨ Feat, ⚙ Chore

#30 Feat: authCheck(test)
  server/controllers/authController.js
  server/routes/auth.js
  server/services/auth.js
Labels: 📬 API, ✨ Feat

#31 Fix: authCheck 응답 데이터 수정
  server/controllers/authController.js
Labels: 📬 API, 🐞 Fix

#32 Rename: tokenModel -> Token
  server/loaders/index.js
  server/services/token.js
Labels: 🔨 Refactor, ⚙ Chore

#33 Fix: authCheck시 비밀번호 노출 수정
  server/loaders/express.js
  server/services/auth.js
  server/services/index.js
  server/services/product.js
  server/services/user.js
Labels: 📬 API, 🐞 Fix

#34 Feat: productRoute, productController
  server/controllers/index.js
  server/controllers/prodController.js
  server/controllers/productController.js
  server/routes/product.js
Labels: 📬 API, ✨ Feat

#35 Feat: productService 함수 추가
  server/controllers/productController.js
  server/middlewares/isAuth.js
  server/services/auth.js
  server/services/product.js
  server/services/token.js
  server/services/user.js
Labels: 📬 API, 🐞 Fix, ✨ Feat

#36 Refactor: catchAsync try-catch문 중복 제거
  server/utils/catchAsync.js
Labels: 📬 API, 🔨 Refactor

#37 Feat: 로그인 및 회원가입 로직 설정
  client/src/_actions/type.js
  client/src/_actions/user_action.js
  client/src/_reducers/user_reducer.js
  client/src/components/Auth/Login.js
  client/src/components/Auth/Register.js
  client/src/components/Layout/Header.js
  client/src/components/Layout/UserAuth.js
  client/src/components/Layout/UserAuth.module.css
  client/src/hoc/auth.js
Labels: 🌈 Frontend, 🔨 Refactor, ✨ Feat

#38 Refactor: 서비스 계층 에러
  server/controllers/authController.js
  server/routes/auth.js
  server/services/auth.js
  server/services/token.js
  server/utils/catchAsync.js
Labels: 📬 API, 🐞 Fix, 🔨 Refactor

#39 Feat: 로그인시 로그아웃, 로그아웃시 로그인/회원가입뜨게하기
  client/src/App.js
  client/src/_actions/user_action.js
  client/src/components/Auth/Login.js
  client/src/components/Layout/Header.js
  client/src/components/Layout/UserAuth.js
  client/src/components/Layout/UserAuth.module.css
  client/src/components/Purchase/Purchase.js
  client/src/components/Purchase/PurchaseCard.js
  client/src/components/Purchase/PurchaseCard.module.css
Labels: 🌈 Frontend, 🎨 Design, 🔨 Refactor, ✨ Feat

#40 Feat: accessToken 제거코드, Refactor: auth 함수
  client/src/_actions/user_action.js
  client/src/hoc/auth.js
Labels: 🌈 Frontend, 🔨 Refactor, ✨ Feat

#43 Feat: product route, model, service, controller 수정 및 일부 구현
  server/.env.example
  server/controllers/authController.js
  server/controllers/productController.js
  server/loaders/express.js
  server/middlewares/error.js
  server/middlewares/index.js
  server/middlewares/isAuth.js
  server/models/product.js
  server/models/user.js
  server/routes/product.js
  server/services/product.js
  server/utils/generalError.js
Labels: 📬 API, ✨ Feat, ⚙ Chore

#46 Fix: 토큰 중복생성 수정
  server/services/auth.js
Labels: 📬 API, 🚑️ Critical

#49 Refactor: loginUser 에러catch, onImgFileHandler, onSubmitHandler, onLogoutHandler, Feat:deleteImgHandler, AuthenticationCheck return, 유효성 검사,
  client/src/_actions/user_action.js
  client/src/components/AddProduct/AddProduct.js
  client/src/components/AddProduct/AddProduct.module.css
  client/src/components/Auth/Login.js
  client/src/components/Layout/UserAuth.js
  client/src/hoc/auth.js
Labels: 🌈 Frontend, 🎨 Design, 🔨 Refactor, ✨ Feat

#50 Refactor: action logout함수 추가 및 리팩토링
  client/.env.development.local.example
  client/src/_actions/type.js
  client/src/_actions/user_action.js
  client/src/_reducers/user_reducer.js
  client/src/components/AddProduct/AddProduct.js
  client/src/components/Auth/Login.js
  client/src/components/Auth/Register.js
  client/src/components/Layout/UserAuth.js
  client/src/setupProxy.js
Labels: 🌈 Frontend, 🐞 Fix, 🔨 Refactor, ⚙ Chore

#51 Fix: action 함수 오타 수정
  client/src/_actions/user_action.js
Labels: 🌈 Frontend, 🐞 Fix

#52 Fix: token 여부 검사 로직 수정
  client/src/App.js
Labels: 🌈 Frontend, 🐞 Fix

#53 Feat: cors옵션 추가, config 도메인추가
  server/config/index.js
  server/loaders/express.js
Labels: 📬 API, ✨ Feat, ⚙ Chore

#54 Feat: secure middleware 구현
  server/config/index.js
  server/controllers/authController.js
  server/loaders/express.js
  server/middlewares/index.js
  server/middlewares/secure.js
  server/routes/auth.js
  server/routes/product.js
Labels: 📬 API, 🐞 Fix, 🔨 Refactor, ✨ Feat

#55 Refactor: signupController, signupService, tokenService, userService
  server/controllers/authController.js
  server/services/auth.js
  server/services/token.js
  server/services/user.js
Labels: 📬 API, 🔨 Refactor

#56 Refactor: login, register, action
  client/src/_actions/user_action.js
  client/src/components/Auth/Login.js
  client/src/components/Auth/Register.js
Labels: 🌈 Frontend, 🔨 Refactor

#57 Refactor: tokenService
  server/services/token.js
Labels: 📬 API, 🔨 Refactor

#58 Refactor: action baseURL 설정
  client/src/_actions/user_action.js
Labels: 🌈 Frontend, 🔨 Refactor

#59 Fix: auth 요청 캐싱문제 수정
  server/.env.example
  server/config/index.js
  server/config/passport.js
  server/controllers/authController.js
  server/middlewares/isAuth.js
  server/services/auth.js
  server/services/token.js
Labels: 📬 API, 🐞 Fix, 🔨 Refactor

#60 Refactor: action 함수
  client/src/App.js
  client/src/_actions/user_action.js
Labels: 🌈 Frontend, 🐞 Fix, 🔨 Refactor

#61 Fix: 로그인 검사 수정
  client/src/App.js
Labels: 🌈 Frontend, 🐞 Fix

#62 Fix: title, favicon, 캐싱 비활성화 등
  client/public/favicon.ico
  client/public/index.html
  client/src/_actions/user_action.js
  client/src/components/AddProduct/AddProduct.js
  client/src/components/Auth/Login.js
  client/src/components/Auth/Register.js
  client/src/components/Layout/Header.js
  client/src/components/Layout/UserAuth.js
  client/src/hoc/auth.js
Labels: 🌈 Frontend, 🐞 Fix, ⚙ Chore

#64 Fix: token 만료기간, 오타, auth 미들웨어 쿠키여부
  server/.env.development.example
  server/.env.example
  server/config/index.js
  server/middlewares/error.js
  server/middlewares/isAuth.js
  server/services/auth.js
  server/services/token.js
Labels: 📬 API, 🐞 Fix

#65 Fix: 경로 오타 수정
  client/src/components/Auth/Register.js
Labels: 🌈 Frontend, 🐞 Fix

#68 Feat: product_action, ADD_PRODUCT type, reducer(ADD_PRODUCT), imgSilde, react-slick, Refactor: useState 현재상태함수, onSubmitHandler, className, Design: CSS, img추가
  client/src/_actions/product_action.js
  client/src/_actions/type.js
  client/src/_reducers/user_reducer.js
  client/src/assets/mainImg.png
  client/src/components/AddProduct/AddProduct.js
  client/src/components/Home/Home.js
  client/src/components/Home/Home.module.css
  client/src/components/Home/Silde.js
  client/src/components/Home/Silde.module.css
  client/src/components/Layout/Header.js
  client/src/components/Layout/Header.module.css
  package-lock.json
  package.json
Labels: 🌈 Frontend, 🎨 Design, 🔨 Refactor, ✨ Feat

#69 Feat: react-slick, slick-carousel
  client/package-lock.json
  client/package.json
  package-lock.json
  package.json
Labels: 🐞 Fix, ✨ Feat

#71 Feat: uploader추가
  server/config/index.js
  server/config/passport.js
  server/controllers/authController.js
  server/controllers/productController.js
  server/loaders/express.js
  server/middlewares/error.js
  server/middlewares/index.js
  server/middlewares/isAuth.js
  server/middlewares/uploader.js
  server/routes/auth.js
  server/routes/index.js
  server/routes/product.js
  server/services/auth.js
  server/services/product.js
  server/services/token.js
  server/utils/index.js
  server/utils/s3Upload.js
Labels: 📬 API, 🐞 Fix, 🔨 Refactor, ✨ Feat

#74 Chore: aws-sdk v3로 수정, 선언부 수정
  server/config/index.js
  server/loaders/sequelize.js
  server/middlewares/uploader.js
  server/package-lock.json
  server/package.json
  server/routes/product.js
  server/utils/s3Upload.js
Labels: 📬 API, ⚙ Chore

#75 Feat: addProduct formData 추가, product action 추가
  client/src/_actions/product_action.js
  client/src/components/AddProduct/AddProduct.js
  client/src/components/Home/Home.js
Labels: 🌈 Frontend, ✨ Feat

#76 Fix: error test
  client/src/_actions/product_action.js
Labels: 🌈 Frontend, 🐞 Fix

#78 Fix: upload middleware 수정
  server/middlewares/uploader.js
  server/routes/product.js
  server/utils/s3Upload.js
Labels: 📬 API, 🐞 Fix

#79 Feat: addProduct action 헤더 추가, upload 필드 수정
  client/src/_actions/product_action.js
  client/src/_actions/user_action.js
  client/src/components/AddProduct/AddProduct.js
  client/src/components/Purchase/Purchase.js
Labels: 🌈 Frontend, 🐞 Fix, ✨ Feat

#80 Fix: auth 토큰 재발급 로직 오류 수정
  server/middlewares/isAuth.js
  server/middlewares/uploader.js
  server/routes/product.js
Labels: 📬 API, 🐞 Fix

#81 Design: 상품 상세페이지 상품정보 및 상점정보
  client/src/components/Purchase/Detail.js
  client/src/components/Purchase/Detail.module.css
  client/src/components/Purchase/PurchaseCard.module.css
Labels: 🌈 Frontend, 🎨 Design

#83 Refactor: props제거 redux store사용, reducer 분할
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/_actions/type.js
  client/src/_reducers/index.js
  client/src/_reducers/productReducer.js
  client/src/_reducers/userReducer.js
  client/src/components/AddProduct/AddProduct.js
  client/src/components/Auth/Login.js
  client/src/components/Layout/Header.js
  client/src/components/Layout/UserAuth.js
  client/src/index.js
Labels: 🌈 Frontend, 🔨 Refactor

#84 Feat: InternalServerError, image삭제 기능, getImgUrlByKey 기능 추가
  server/controllers/productController.js
  server/loaders/sequelize.js
  server/middlewares/isAuth.js
  server/middlewares/uploader.js
  server/routes/product.js
  server/utils/generalError.js
  server/utils/index.js
  server/utils/s3Upload.js
Labels: 📬 API, 🐞 Fix, ✨ Feat, ⚙ Chore
