Repository legm0310/SafeTransactionPlatform, pull requests merged in 2023-09, with the labels that each got.

#153 Rename: 파일 위치 변경
  client/package-lock.json
  client/package.json
  client/src/components/product/RecentProducts.js
  client/src/components/user/OnSaleProduct.js
  client/src/components/user/PurchasedProduct.js
  client/src/components/user/ReservedProduct.js
  client/src/components/user/WishList.js
  client/src/pages/User/UserInfo.js
  client/src/pages/User/WishList.js
  client/src/setupProxy.js
  client/src/styles/product/RecentProducts.module.css
  client/src/styles/user/UserInfo.module.css
  client/src/styles/user/WishList.module.css
Labels: 🌈 Frontend, 🎨 Design, 🔀 Merge, ✨ Feat

#154 Feat: 채팅기능
  client/src/components/chat/Chatroom.js
  client/src/components/chat/Chats.js
  client/src/components/chat/Message.js
  client/src/components/chat/Search.js
  client/src/components/chat/Sidebar.js
  client/src/pages/Chat/Chat.js
  client/src/pages/Chat/Input.js
  client/src/pages/Chat/Messages.js
  client/src/setupProxy.js
Labels: 🌈 Frontend, 🐞 Fix, 🎨 Design, ✨ Feat

#155 Design: 찜목록 디자인
  client/src/components/user/WishList.js
  client/src/styles/user/UserInfo.module.css
  client/src/styles/user/WishList.module.css
Labels: 🌈 Frontend, 🎨 Design

#156 Merge: client -> dev
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/_actions/chatAction.js
  client/src/_actions/type.js
  client/src/_reducers/chatReducer.js
  client/src/_reducers/index.js
  client/src/components/chat/Chatroom.js
  client/src/components/chat/Chats.js
  client/src/components/chat/Message.js
  client/src/components/chat/Search.js
  client/src/components/chat/Sidebar.js
  client/src/components/product/RecentProducts.js
  client/src/components/user/OnSaleProduct.js
  client/src/components/user/PurchasedProduct.js
  client/src/components/user/ReservedProduct.js
  client/src/components/user/WishList.js
  client/src/config/dappOptions.js
  client/src/index.js
  client/src/pages/Chat/Chat.js
  client/src/pages/Product/CategoryBar.js
  client/src/pages/Product/Product.js
  client/src/pages/User/UserInfo.js
  client/src/pages/User/WishList.js
  client/src/styles/auth/Login.module.css
  client/src/styles/chat/Chat.module.css
  client/src/styles/product/Product.module.css
  client/src/styles/product/ReactMinimalSideNavigation.css
  client/src/styles/product/RecentProducts.module.css
  client/src/styles/user/UserInfo.module.css
  client/src/styles/user/WishList.module.css
Labels: 🌈 Frontend, 🔀 Merge

#158 Merge: dev -> main
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/_actions/chatAction.js
  client/src/_actions/type.js
  client/src/_reducers/chatReducer.js
  client/src/_reducers/index.js
  client/src/components/chat/Chatroom.js
  client/src/components/chat/Chats.js
  client/src/components/chat/Message.js
  client/src/components/chat/Search.js
  client/src/components/chat/Sidebar.js
  client/src/components/product/RecentProducts.js
  client/src/components/user/OnSaleProduct.js
  client/src/components/user/PurchasedProduct.js
  client/src/components/user/ReservedProduct.js
  client/src/components/user/WishList.js
  client/src/config/dappOptions.js
  client/src/index.js
  client/src/pages/Chat/Chat.js
  client/src/pages/Product/CategoryBar.js
  client/src/pages/Product/Product.js
  client/src/pages/User/UserInfo.js
  client/src/pages/User/WishList.js
  client/src/styles/auth/Login.module.css
  client/src/styles/chat/Chat.module.css
  client/src/styles/product/Product.module.css
  client/src/styles/product/ReactMinimalSideNavigation.css
  client/src/styles/product/RecentProducts.module.css
  client/src/styles/user/UserInfo.module.css
  client/src/styles/user/WishList.module.css
  server/config/validSchema.js
  server/controllers/chatController.js
  server/ecosystem.config.js
  server/loaders/sequelize.js
  server/loaders/socket.js
  server/models/catagory.js
  server/models/chatLog.js
  server/models/chatParticipant.js
  server/models/chatRoom.js
  server/models/index.js
  server/models/product.js
  server/models/token.js
  server/models/user.js
  server/models/wishList.js
  server/package.json
  server/routes/chat.js
Labels: 📬 API, 🌈 Frontend, 🔀 Merge

#159 찜목록 기능 추가
  client/src/App.js
  client/src/assets/icon-delete.svg
  client/src/components/headers/Header.js
  client/src/components/headers/UserAuth.js
  client/src/components/user/Wish.js
  client/src/components/user/WishList.js
  client/src/pages/Product/Detail.js
  client/src/pages/User/UserInfo.js
  client/src/styles/user/UserInfo.module.css
  client/src/styles/user/WishList.module.css
Labels: 🌈 Frontend, 🎨 Design, ✨ Feat

#160 Feat: 메시지 DB에 저장 기능 추가
  client/src/_actions/chatAction.js
  client/src/_actions/type.js
  client/src/_reducers/chatReducer.js
  client/src/components/chat/Chatroom.js
  client/src/pages/Product/Detail.js
Labels: 🌈 Frontend, ✨ Feat

#161 Feat: 메시지 DB에 저장 기능 추가
  server/controllers/chatController.js
  server/controllers/productController.js
  server/models/chatLog.js
  server/models/product.js
  server/routes/chat.js
  server/routes/product.js
  server/services/chat.js
  server/services/product.js
Labels: 📬 API, ✨ Feat

#162 Feat: WishList GET / POST / DELETE API 추가
  server/controllers/productController.js
  server/loaders/sequelize.js
  server/routes/product.js
  server/services/product.js
Labels: 📬 API, ✨ Feat

#163 Feat: Notice 컴포넌트 구조 생성
  client/src/App.js
  client/src/assets/testImg.png
  client/src/assets/testImg1.png
  client/src/components/notice/Notice_1.js
  client/src/components/notice/Notice_2.js
  client/src/components/notice/Notice_3.js
  client/src/components/notice/Notice_4.js
  client/src/components/notice/Notice_5.js
  client/src/components/notice/Notice_6.js
  client/src/pages/Home/HomeSlide.js
  client/src/pages/Notice/Notice.js
  client/src/styles/home/HomeSlide.module.css
  client/src/styles/notice/Notice.module.css
Labels: 🌈 Frontend, ✨ Feat

#164 Rename: 파스칼케이스로 변경
  client/src/components/chat/Chatroom.js
  client/src/pages/Chat/Chat.js
Labels: 🌈 Frontend

#165 Refactor: wishList 관련 함수 product에서 user로 이동
  server/controllers/index.js
  server/controllers/productController.js
  server/controllers/userController.js
  server/loaders/socket.js
  server/routes/index.js
  server/routes/product.js
  server/routes/user.js
  server/services/product.js
  server/services/user.js
Labels: 📬 API, 🔨 Refactor

#166 Refactor: getWishList 메소드 utils 메소드 이용하게 수정
  server/services/user.js
  server/utils/socketHandler.js
Labels: 📬 API, 🔨 Refactor

#167 Feat: wishlist redux
  client/src/_actions/type.js
  client/src/_actions/userAction.js
  client/src/_reducers/userReducer.js
  client/src/components/chat/ChatRoom.js
  client/src/components/user/OnSaleProduct.js
  client/src/components/user/PurchasedProduct.js
  client/src/components/user/ReservedProduct.js
  client/src/pages/Product/Detail.js
  client/src/pages/User/UserInfo.js
  client/src/styles/product/Detail.module.css
  client/src/styles/product/RecentProducts.module.css
  client/src/styles/user/OnSaleProduct.module.css
  client/src/styles/user/PurchasedProduct.module.css
  client/src/styles/user/ReservedProduct.module.css
  client/src/styles/user/UserInfo.module.css
Labels: 🌈 Frontend, 🎨 Design, 🔀 Merge, ✨ Feat

#168 Feat: 찜목록 기능 구현
  client/src/_actions/type.js
  client/src/_actions/userAction.js
  client/src/_reducers/userReducer.js
  client/src/components/chat/ChatRoom.js
  client/src/components/user/Wish.js
  client/src/components/user/WishItem.js
  client/src/components/user/WishList.js
  client/src/pages/AddProduct/AddProduct.js
  client/src/pages/Product/Detail.js
  client/src/pages/User/UserInfo.js
Labels: 🌈 Frontend, 🎨 Design, ✨ Feat

#170 Feat: 찜목록 Delete기능
  client/src/_actions/type.js
  client/src/_actions/userAction.js
  client/src/_reducers/userReducer.js
  client/src/components/user/SaleItem.js
  client/src/components/user/SaleList.js
  client/src/components/user/WishItem.js
  client/src/pages/Product/Detail.js
Labels: 🌈 Frontend, 🎨 Design, 🔨 Refactor, 🔀 Merge, ✨ Feat

#171 Feat: 카테고리별 검색 기능 추가
  client/src/_actions/productAction.js
  client/src/_actions/type.js
  client/src/pages/Product/CategoryBar.js
  client/src/pages/Product/Product.js
  client/src/pages/Product/ProductCard.js
  client/src/pages/User/UserInfo.js
Labels: 🌈 Frontend, ✨ Feat

#172 Feat: ProductCard API 연동
  client/src/pages/Product/Product.js
  client/src/pages/Product/ProductCard.js
Labels: 🌈 Frontend, ✨ Feat

#173 Feat: Product Generate에 Select category 추가
  server/loaders/sequelize.js
  server/models/category.js
  server/models/index.js
  server/utils/dataParsers.js
Labels: 📬 API, ✨ Feat

#174 Feat: 구매하기 URL에 파라미터 기본값 추가 및 검색 기능 보완
  client/src/_actions/productAction.js
  client/src/components/headers/DesktopNavMenu.js
  client/src/components/headers/MobileNavMenu.js
  client/src/pages/Product/Product.js
Labels: 🌈 Frontend, ✨ Feat

#175 Merge: 병합충돌해결
  client/src/App.js
  client/src/_actions/chatAction.js
  client/src/_actions/type.js
  client/src/_reducers/chatReducer.js
  client/src/_reducers/userReducer.js
  client/src/components/Home/HomeSlide.js
  client/src/components/detailProduct/DetailSlide.js
  client/src/components/detailProduct/ProductInformation.js
  client/src/components/detailProduct/ProductStore.js
  client/src/components/headers/UserMenu.js
  client/src/components/product/CategoryBar.js
  client/src/components/product/ProductCard.js
  client/src/components/user/WishList.js
  client/src/pages/DetailProduct/Detail.js
  client/src/pages/Home/Home.js
  client/src/pages/Product/Product.js
  client/src/pages/User/UserInfo.js
Labels: 🌈 Frontend, 🎨 Design, 🔀 Merge, ✨ Feat
