Repository legm0310/SafeTransactionPlatform, pull requests merged in 2023-08, with the labels that each got.

#146 Merge: server -> dev
  server/controllers/chatController.js
  server/models/user.js
Labels: 📬 API, 🔀 Merge

#147 Merge: dev -> main
  server/controllers/chatController.js
  server/loaders/dependencyInjector.js
  server/loaders/sequelize.js
  server/models/catagory.js
  server/models/chatRoom.js
  server/models/index.js
  server/models/product.js
  server/models/token.js
  server/models/user.js
  server/models/wishList.js
  server/models/wishLists.js
  server/routes/auth.js
  server/routes/chat.js
  server/routes/product.js
  server/services/chat.js
  server/utils/socketHandler.js
Labels: 📬 API, 🌈 Frontend, 🔀 Merge

#148 카테고리 사이드바, 판다톡 채팅방 디자인
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/pages/Chat/Chat.js
  client/src/pages/Chat/Chatroom.js
  client/src/pages/Chat/Chats.js
  client/src/pages/Chat/Input.js
  client/src/pages/Chat/Message.js
  client/src/pages/Chat/Messages.js
  client/src/pages/Chat/Search.js
  client/src/pages/Chat/Sidebar.js
  client/src/pages/Product/CategoryBar.js
  client/src/pages/Product/Product.js
  client/src/pages/User/ReservedProduct.js
  client/src/styles/auth/Login.module.css
  client/src/styles/chat/Chat.module.css
  client/src/styles/product/Product.module.css
  client/src/styles/product/ReactMinimalSideNavigation.css
  client/src/styles/product/RecentProducts.module.css
Labels: 🌈 Frontend, 🎨 Design, ✨ Feat
